# Generated by Django 4.2.21 on 2025-05-29 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='bio',
        ),
        migrations.AddField(
            model_name='myuser',
            name='about',
            field=models.TextField(blank=True, help_text='Заполните информацию в блоке', max_length=500, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.SmallIntegerField(blank=True, help_text='Заполните информацию в блоке', null=True, validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение - 1'), django.core.validators.MaxValueValidator(100, 'Максималое значение - 100')], verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], help_text='Заполните информацию в блоке', null=True, verbose_name='Ссылка на профиль в ТГ'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='tg_link',
            field=models.URLField(blank=True, help_text='Заполните информацию в блоке', null=True, verbose_name='Ссылка на профиль в ТГ'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='vk_link',
            field=models.URLField(blank=True, help_text='Заполните информацию в блоке', null=True, verbose_name='Ссылка на профиль в ВК'),
        ),
    ]
