# Generated by Django 4.2.21 on 2025-05-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_myuser_bio_myuser_about_myuser_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, choices=[('London', 'Лондон'), ('Paris', 'Париж'), ('Berlin', 'Берлин'), ('Rome', 'Рим'), ('Madrid', 'Мадрид'), ('Amsterdam', 'Амстердам'), ('Tokyo', 'Токио'), ('New York', 'Нью-Йорк'), ('Sydney', 'Сидней'), ('Vienna', 'Вена')], help_text='Заполните информацию в блоке', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='instrument',
            field=models.CharField(blank=True, choices=[('Piano', 'Фортепиано'), ('Violin', 'Скрипка'), ('Guitar', 'Гитара'), ('Drums', 'Ударные'), ('Flute', 'Флейта'), ('Trumpet', 'Труба'), ('Cello', 'Виолончель'), ('Clarinet', 'Кларнет'), ('Harp', 'Арфа'), ('Accordion', 'Аккордеон')], help_text='Заполните информацию в блоке', max_length=100, null=True, verbose_name='Инструмент'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='purpose',
            field=models.CharField(blank=True, choices=[('FindBand', 'Найти музыкальную группу'), ('ImproveSkills', 'Повысить уровень игры'), ('EarnMoney', 'Получить доход'), ('CoverGroup', 'Играть в кавер-группе'), ('BookConcerts', 'Забронировать концерты'), ('SellEquipment', 'Продажа музыкального оборудования'), ('TeachingLessons', 'Обучение игре на инструменте'), ('RecordMusic', 'Запись музыки в студии'), ('Networking', 'Создание профессиональных связей'), ('DiscoverOpportunities', 'Открытие новых возможностей')], help_text='Заполните информацию в блоке', max_length=100, null=True, verbose_name='Цель'),
        ),
    ]
