# Generated by Django 4.2.21 on 2025-05-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_city_myuser_instrument_myuser_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='users_photo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (5, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Заполните информацию в блоке', null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Заполните информацию в блоке', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.photo', verbose_name='Фотография'),
        ),
    ]
