# Generated by Django 4.2.21 on 2025-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_photo_alter_myuser_options_alter_myuser_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='photo',
        ),
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.ManyToManyField(blank=True, help_text='Заполните информацию в блоке', to='users.photo', verbose_name='Фотография'),
        ),
    ]
