# Generated by Django 4.2.21 on 2025-05-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_myuser_photo_myuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='users_audio')),
            ],
            options={
                'verbose_name': 'Аудиозапись',
                'verbose_name_plural': 'Аудиозаписи',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='users_video')),
            ],
            options={
                'verbose_name': 'Видеозапись',
                'verbose_name_plural': 'Видеозаписи',
            },
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='audio',
            field=models.ManyToManyField(blank=True, help_text='Заполните информацию в блоке', to='users.audio', verbose_name='Аудиозапись'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='video',
            field=models.ManyToManyField(blank=True, help_text='Заполните информацию в блоке', to='users.video', verbose_name='Видеозапись'),
        ),
    ]
