# Generated by Django 4.2.21 on 2025-05-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_audio_video_alter_photo_options_myuser_audio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='instrument',
            new_name='instrument_1',
        ),
        migrations.AddField(
            model_name='myuser',
            name='instrument_2',
            field=models.CharField(blank=True, choices=[('Piano', 'Фортепиано'), ('Violin', 'Скрипка'), ('Guitar', 'Гитара'), ('Drums', 'Ударные'), ('Flute', 'Флейта'), ('Trumpet', 'Труба'), ('Cello', 'Виолончель'), ('Clarinet', 'Кларнет'), ('Harp', 'Арфа'), ('Accordion', 'Аккордеон')], help_text='Заполните информацию в блоке', max_length=100, null=True, verbose_name='Инструмент'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='instrument_3',
            field=models.CharField(blank=True, choices=[('Piano', 'Фортепиано'), ('Violin', 'Скрипка'), ('Guitar', 'Гитара'), ('Drums', 'Ударные'), ('Flute', 'Флейта'), ('Trumpet', 'Труба'), ('Cello', 'Виолончель'), ('Clarinet', 'Кларнет'), ('Harp', 'Арфа'), ('Accordion', 'Аккордеон')], help_text='Заполните информацию в блоке', max_length=100, null=True, verbose_name='Инструмент'),
        ),
        migrations.AddConstraint(
            model_name='myuser',
            constraint=models.UniqueConstraint(fields=('instrument_1', 'instrument_2', 'instrument_3'), name='unique_instruments'),
        ),
    ]
