# Generated by Django 4.2.21 on 2025-05-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_instrument_myuser_instrument_1_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='myuser',
            name='unique_instruments',
        ),
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default=1, help_text='Заполните информацию в блоке', upload_to='users_avatars', verbose_name='Аватар'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='instrument_1',
            field=models.CharField(blank=True, choices=[('Piano', 'Фортепиано'), ('Violin', 'Скрипка'), ('Guitar', 'Гитара'), ('Drums', 'Ударные'), ('Flute', 'Флейта'), ('Trumpet', 'Труба'), ('Cello', 'Виолончель'), ('Clarinet', 'Кларнет'), ('Harp', 'Арфа'), ('Accordion', 'Аккордеон')], help_text='Заполните информацию в блоке', max_length=100, null=True, verbose_name='Инструмент 1'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='instrument_2',
            field=models.CharField(blank=True, choices=[('Piano', 'Фортепиано'), ('Violin', 'Скрипка'), ('Guitar', 'Гитара'), ('Drums', 'Ударные'), ('Flute', 'Флейта'), ('Trumpet', 'Труба'), ('Cello', 'Виолончель'), ('Clarinet', 'Кларнет'), ('Harp', 'Арфа'), ('Accordion', 'Аккордеон')], help_text='Заполните информацию в блоке', max_length=100, null=True, verbose_name='Инструмент 2'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='instrument_3',
            field=models.CharField(blank=True, choices=[('Piano', 'Фортепиано'), ('Violin', 'Скрипка'), ('Guitar', 'Гитара'), ('Drums', 'Ударные'), ('Flute', 'Флейта'), ('Trumpet', 'Труба'), ('Cello', 'Виолончель'), ('Clarinet', 'Кларнет'), ('Harp', 'Арфа'), ('Accordion', 'Аккордеон')], help_text='Заполните информацию в блоке', max_length=100, null=True, verbose_name='Инструмент 3'),
        ),
    ]
